export enum TcfCaV2Field {
  VERSION = "Version",
  CREATED = "Created",
  LAST_UPDATED = "LastUpdated",
  CMP_ID = "CmpId",
  CMP_VERSION = "CmpVersion",
  CONSENT_SCREEN = "ConsentScreen",
  CONSENT_LANGUAGE = "ConsentLanguage",
  VENDOR_LIST_VERSION = "VendorListVersion",
  TCF_POLICY_VERSION = "TcfPolicyVersion",
  USE_NON_STANDARD_STACKS = "UseNonStandardStacks",
  SPECIAL_FEATURE_EXPRESS_CONSENT = "SpecialFeatureExpressConsent",
  PURPOSES_EXPRESS_CONSENT = "PurposesExpressConsent",
  PURPOSES_IMPLIED_CONSENT = "PurposesImpliedConsent",
  VENDOR_EXPRESS_CONSENT = "VendorExpressConsent",
  VENDOR_IMPLIED_CONSENT = "VendorImpliedConsent",
  SEGMENT_TYPE = "SegmentType",
  PUB_PURPOSES_EXPRESS_CONSENT = "PubPurposesExpressConsent",
  PUB_PURPOSES_IMPLIED_CONSENT = "PubPurposesImpliedConsent",
  NUM_CUSTOM_PURPOSES = "NumCustomPurposes",
  CUSTOM_PURPOSES_EXPRESS_CONSENT = "CustomPurposesExpressConsent",
  CUSTOM_PURPOSES_IMPLIED_CONSENT = "CustomPurposesImpliedConsent",
}
