export enum TcfEuV2Field {
  VERSION = "Version",
  CREATED = "Created",
  LAST_UPDATED = "LastUpdated",
  CMP_ID = "CmpId",
  CMP_VERSION = "CmpVersion",
  CONSENT_SCREEN = "ConsentScreen",
  CONSENT_LANGUAGE = "ConsentLanguage",
  VENDOR_LIST_VERSION = "VendorListVersion",
  POLICY_VERSION = "PolicyVersion",
  IS_SERVICE_SPECIFIC = "IsServiceSpecific",
  USE_NON_STANDARD_STACKS = "UseNonStandardStacks",
  SPECIAL_FEATURE_OPTINS = "SpecialFeatureOptins",
  PURPOSE_CONSENTS = "PurposeConsents",
  PURPOSE_LEGITIMATE_INTERESTS = "PurposeLegitimateInterests",
  PURPOSE_ONE_TREATMENT = "PurposeOneTreatment",
  PUBLISHER_COUNTRY_CODE = "PublisherCountryCode",
  VENDOR_CONSENTS = "VendorConsents",
  VENDOR_LEGITIMATE_INTERESTS = "VendorLegitimateInterests",
  PUBLISHER_RESTRICTIONS = "PublisherRestrictions",
  PUBLISHER_PURPOSES_SEGMENT_TYPE = "PublisherPurposesSegmentType",
  PUBLISHER_CONSENTS = "PublisherConsents",
  PUBLISHER_LEGITIMATE_INTERESTS = "PublisherLegitimateInterests",
  NUM_CUSTOM_PURPOSES = "NumCustomPurposes",
  PUBLISHER_CUSTOM_CONSENTS = "PublisherCustomConsents",
  PUBLISHER_CUSTOM_LEGITIMATE_INTERESTS = "PublisherCustomLegitimateInterests",
  VENDORS_ALLOWED_SEGMENT_TYPE = "VendorsAllowedSegmentType",
  VENDORS_ALLOWED = "VendorsAllowed",
  VENDORS_DISCLOSED_SEGMENT_TYPE = "VendorsDisclosedSegmentType",
  VENDORS_DISCLOSED = "VendorsDisclosed",
}

export const TCFEUV2_CORE_SEGMENT_FIELD_NAMES = [
  TcfEuV2Field.VERSION,
  TcfEuV2Field.CREATED,
  TcfEuV2Field.LAST_UPDATED,
  TcfEuV2Field.CMP_ID,
  TcfEuV2Field.CMP_VERSION,
  TcfEuV2Field.CONSENT_SCREEN,
  TcfEuV2Field.CONSENT_LANGUAGE,
  TcfEuV2Field.VENDOR_LIST_VERSION,
  TcfEuV2Field.POLICY_VERSION,
  TcfEuV2Field.IS_SERVICE_SPECIFIC,
  TcfEuV2Field.USE_NON_STANDARD_STACKS,
  TcfEuV2Field.SPECIAL_FEATURE_OPTINS,
  TcfEuV2Field.PURPOSE_CONSENTS,
  TcfEuV2Field.PURPOSE_LEGITIMATE_INTERESTS,
  TcfEuV2Field.PURPOSE_ONE_TREATMENT,
  TcfEuV2Field.PUBLISHER_COUNTRY_CODE,
  TcfEuV2Field.VENDOR_CONSENTS,
  TcfEuV2Field.VENDOR_LEGITIMATE_INTERESTS,
  TcfEuV2Field.PUBLISHER_RESTRICTIONS,
];

export const TCFEUV2_PUBLISHER_PURPOSES_SEGMENT_FIELD_NAMES = [
  TcfEuV2Field.PUBLISHER_PURPOSES_SEGMENT_TYPE,
  TcfEuV2Field.PUBLISHER_CONSENTS,
  TcfEuV2Field.PUBLISHER_LEGITIMATE_INTERESTS,
  TcfEuV2Field.NUM_CUSTOM_PURPOSES,
  TcfEuV2Field.PUBLISHER_CUSTOM_CONSENTS,
  TcfEuV2Field.PUBLISHER_CUSTOM_LEGITIMATE_INTERESTS,
];

export const TCFEUV2_VENDORS_ALLOWED_SEGMENT_FIELD_NAMES = [
  TcfEuV2Field.VENDORS_ALLOWED_SEGMENT_TYPE,
  TcfEuV2Field.VENDORS_ALLOWED,
];

export const TCFEUV2_VENDORS_DISCLOSED_SEGMENT_FIELD_NAMES = [
  TcfEuV2Field.VENDORS_DISCLOSED_SEGMENT_TYPE,
  TcfEuV2Field.VENDORS_DISCLOSED,
];
