export enum UsCaV1Field {
  VERSION = "Version",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  SHARING_OPT_OUT_NOTICE = "SharingOptOutNotice",
  SENSITIVE_DATA_LIMIT_USE_NOTICE = "SensitiveDataLimitUseNotice",
  SALE_OPT_OUT = "SaleOptOut",
  SHARING_OPT_OUT = "SharingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  PERSONAL_DATA_CONSENTS = "PersonalDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USCAV1_CORE_SEGMENT_FIELD_NAMES = [
  UsCaV1Field.VERSION,
  UsCaV1Field.SALE_OPT_OUT_NOTICE,
  UsCaV1Field.SHARING_OPT_OUT_NOTICE,
  UsCaV1Field.SENSITIVE_DATA_LIMIT_USE_NOTICE,
  UsCaV1Field.SALE_OPT_OUT,
  UsCaV1Field.SHARING_OPT_OUT,
  UsCaV1Field.SENSITIVE_DATA_PROCESSING,
  UsCaV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsCaV1Field.PERSONAL_DATA_CONSENTS,
  UsCaV1Field.MSPA_COVERED_TRANSACTION,
  UsCaV1Field.MSPA_OPT_OUT_OPTION_MODE,
  UsCaV1Field.MSPA_SERVICE_PROVIDER_MODE,
];

export const USCAV1_GPC_SEGMENT_FIELD_NAMES = [UsCaV1Field.GPC_SEGMENT_TYPE, UsCaV1Field.GPC];
