export enum UsCtV1Field {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USCTV1_CORE_SEGMENT_FIELD_NAMES = [
  UsCtV1Field.VERSION,
  UsCtV1Field.SHARING_NOTICE,
  UsCtV1Field.SALE_OPT_OUT_NOTICE,
  UsCtV1Field.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsCtV1Field.SALE_OPT_OUT,
  UsCtV1Field.TARGETED_ADVERTISING_OPT_OUT,
  UsCtV1Field.SENSITIVE_DATA_PROCESSING,
  UsCtV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsCtV1Field.MSPA_COVERED_TRANSACTION,
  UsCtV1Field.MSPA_OPT_OUT_OPTION_MODE,
  UsCtV1Field.MSPA_SERVICE_PROVIDER_MODE,
];

export const USCTV1_GPC_SEGMENT_FIELD_NAMES = [UsCtV1Field.GPC_SEGMENT_TYPE, UsCtV1Field.GPC];
