export enum UsCtField {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USCT_CORE_SEGMENT_FIELD_NAMES = [
  UsCtField.VERSION,
  UsCtField.SHARING_NOTICE,
  UsCtField.SALE_OPT_OUT_NOTICE,
  UsCtField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsCtField.SALE_OPT_OUT,
  UsCtField.TARGETED_ADVERTISING_OPT_OUT,
  UsCtField.SENSITIVE_DATA_PROCESSING,
  UsCtField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsCtField.MSPA_COVERED_TRANSACTION,
  UsCtField.MSPA_OPT_OUT_OPTION_MODE,
  UsCtField.MSPA_SERVICE_PROVIDER_MODE,
];

export const USCT_GPC_SEGMENT_FIELD_NAMES = [UsCtField.GPC_SEGMENT_TYPE, UsCtField.GPC];
