export enum UsKyField {
  MSPA_VERSION = "MspaVersion",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_MODE = "MspaMode",
  PROCESSING_NOTICE = "ProcessingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  ADDITIONAL_DATA_PROCESSING_CONSENT = "AdditionalDataProcessingConsent",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  SENSITIVE_DATA_CONSENT_SEGMENT_INCLUDED = "SensitiveDataConsentSegmentIncluded",
}

export const UsKy_CORE_SEGMENT_FIELD_NAMES = [
  UsKyField.MSPA_VERSION,
  UsKyField.MSPA_COVERED_TRANSACTION,
  UsKyField.MSPA_MODE,
  UsKyField.PROCESSING_NOTICE,
  UsKyField.SALE_OPT_OUT_NOTICE,
  UsKyField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsKyField.SALE_OPT_OUT,
  UsKyField.TARGETED_ADVERTISING_OPT_OUT,
  UsKyField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsKyField.ADDITIONAL_DATA_PROCESSING_CONSENT,
];

export const UsKy_SENSITIVE_DATA_CONSENT_SEGMENT_FIELD_NAMES = [UsKyField.SENSITIVE_DATA_PROCESSING];
