export enum UsMtField {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  ADDITIONAL_DATA_PROCESSING_CONSENT = "AdditionalDataProcessingConsent",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USMT_CORE_SEGMENT_FIELD_NAMES = [
  UsMtField.VERSION,
  UsMtField.SHARING_NOTICE,
  UsMtField.SALE_OPT_OUT_NOTICE,
  UsMtField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsMtField.SALE_OPT_OUT,
  UsMtField.TARGETED_ADVERTISING_OPT_OUT,
  UsMtField.SENSITIVE_DATA_PROCESSING,
  UsMtField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsMtField.ADDITIONAL_DATA_PROCESSING_CONSENT,
  UsMtField.MSPA_COVERED_TRANSACTION,
  UsMtField.MSPA_OPT_OUT_OPTION_MODE,
  UsMtField.MSPA_SERVICE_PROVIDER_MODE,
];

export const USMT_GPC_SEGMENT_FIELD_NAMES = [UsMtField.GPC_SEGMENT_TYPE, UsMtField.GPC];
