export enum UsMtV1Field {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  ADDITIONAL_DATA_PROCESSING_CONSENT = "AdditionalDataProcessingConsent",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USMTV1_CORE_SEGMENT_FIELD_NAMES = [
  UsMtV1Field.VERSION,
  UsMtV1Field.SHARING_NOTICE,
  UsMtV1Field.SALE_OPT_OUT_NOTICE,
  UsMtV1Field.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsMtV1Field.SALE_OPT_OUT,
  UsMtV1Field.TARGETED_ADVERTISING_OPT_OUT,
  UsMtV1Field.SENSITIVE_DATA_PROCESSING,
  UsMtV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsMtV1Field.ADDITIONAL_DATA_PROCESSING_CONSENT,
  UsMtV1Field.MSPA_COVERED_TRANSACTION,
  UsMtV1Field.MSPA_OPT_OUT_OPTION_MODE,
  UsMtV1Field.MSPA_SERVICE_PROVIDER_MODE,
];

export const USMTV1_GPC_SEGMENT_FIELD_NAMES = [UsMtV1Field.GPC_SEGMENT_TYPE, UsMtV1Field.GPC];
