export enum UsNatField {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  SHARING_OPT_OUT_NOTICE = "SharingOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SENSITIVE_DATA_PROCESSING_OPT_OUT_NOTICE = "SensitiveDataProcessingOptOutNotice",
  SENSITIVE_DATA_LIMIT_USE_NOTICE = "SensitiveDataLimitUseNotice",
  SALE_OPT_OUT = "SaleOptOut",
  SHARING_OPT_OUT = "SharingOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  PERSONAL_DATA_CONSENTS = "PersonalDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USNAT_CORE_SEGMENT_FIELD_NAMES = [
  UsNatField.VERSION,
  UsNatField.SHARING_NOTICE,
  UsNatField.SALE_OPT_OUT_NOTICE,
  UsNatField.SHARING_OPT_OUT_NOTICE,
  UsNatField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsNatField.SENSITIVE_DATA_PROCESSING_OPT_OUT_NOTICE,
  UsNatField.SENSITIVE_DATA_LIMIT_USE_NOTICE,
  UsNatField.SALE_OPT_OUT,
  UsNatField.SHARING_OPT_OUT,
  UsNatField.TARGETED_ADVERTISING_OPT_OUT,
  UsNatField.SENSITIVE_DATA_PROCESSING,
  UsNatField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsNatField.PERSONAL_DATA_CONSENTS,
  UsNatField.MSPA_COVERED_TRANSACTION,
  UsNatField.MSPA_OPT_OUT_OPTION_MODE,
  UsNatField.MSPA_SERVICE_PROVIDER_MODE,
];

export const USNAT_GPC_SEGMENT_FIELD_NAMES = [UsNatField.GPC_SEGMENT_TYPE, UsNatField.GPC];
