export enum UsNhField {
  VERSION = "Version",
  PROCESSING_NOTICE = "ProcessingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  ADDITIONAL_DATA_PROCESSING_CONSENT = "AdditionalDataProcessingConsent",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USNH_CORE_SEGMENT_FIELD_NAMES = [
  UsNhField.VERSION,
  UsNhField.PROCESSING_NOTICE,
  UsNhField.SALE_OPT_OUT_NOTICE,
  UsNhField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsNhField.SALE_OPT_OUT,
  UsNhField.TARGETED_ADVERTISING_OPT_OUT,
  UsNhField.SENSITIVE_DATA_PROCESSING,
  UsNhField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsNhField.ADDITIONAL_DATA_PROCESSING_CONSENT,
  UsNhField.MSPA_COVERED_TRANSACTION,
  UsNhField.MSPA_OPT_OUT_OPTION_MODE,
  UsNhField.MSPA_SERVICE_PROVIDER_MODE,
];

export const USNH_GPC_SEGMENT_FIELD_NAMES = [UsNhField.GPC_SEGMENT_TYPE, UsNhField.GPC];
