export enum UsOrV1Field {
  VERSION = "Version",
  PROCESSING_NOTICE = "ProcessingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  ADDITIONAL_DATA_PROCESSING_CONSENT = "AdditionalDataProcessingConsent",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",

  GPC_SEGMENT_TYPE = "GpcSegmentType",
  GPC_SEGMENT_INCLUDED = "GpcSegmentIncluded",
  GPC = "Gpc",
}

export const USORV1_CORE_SEGMENT_FIELD_NAMES = [
  UsOrV1Field.VERSION,
  UsOrV1Field.PROCESSING_NOTICE,
  UsOrV1Field.SALE_OPT_OUT_NOTICE,
  UsOrV1Field.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsOrV1Field.SALE_OPT_OUT,
  UsOrV1Field.TARGETED_ADVERTISING_OPT_OUT,
  UsOrV1Field.SENSITIVE_DATA_PROCESSING,
  UsOrV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsOrV1Field.ADDITIONAL_DATA_PROCESSING_CONSENT,
  UsOrV1Field.MSPA_COVERED_TRANSACTION,
  UsOrV1Field.MSPA_OPT_OUT_OPTION_MODE,
  UsOrV1Field.MSPA_SERVICE_PROVIDER_MODE,
];

export const USORV1_GPC_SEGMENT_FIELD_NAMES = [UsOrV1Field.GPC_SEGMENT_TYPE, UsOrV1Field.GPC];
