export enum UsVaField {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",
}

export const USVA_CORE_SEGMENT_FIELD_NAMES = [
  UsVaField.VERSION,
  UsVaField.SHARING_NOTICE,
  UsVaField.SALE_OPT_OUT_NOTICE,
  UsVaField.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsVaField.SALE_OPT_OUT,
  UsVaField.TARGETED_ADVERTISING_OPT_OUT,
  UsVaField.SENSITIVE_DATA_PROCESSING,
  UsVaField.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsVaField.MSPA_COVERED_TRANSACTION,
  UsVaField.MSPA_OPT_OUT_OPTION_MODE,
  UsVaField.MSPA_SERVICE_PROVIDER_MODE,
];
