export enum UsVaV1Field {
  VERSION = "Version",
  SHARING_NOTICE = "SharingNotice",
  SALE_OPT_OUT_NOTICE = "SaleOptOutNotice",
  TARGETED_ADVERTISING_OPT_OUT_NOTICE = "TargetedAdvertisingOptOutNotice",
  SALE_OPT_OUT = "SaleOptOut",
  TARGETED_ADVERTISING_OPT_OUT = "TargetedAdvertisingOptOut",
  SENSITIVE_DATA_PROCESSING = "SensitiveDataProcessing",
  KNOWN_CHILD_SENSITIVE_DATA_CONSENTS = "KnownChildSensitiveDataConsents",
  MSPA_COVERED_TRANSACTION = "MspaCoveredTransaction",
  MSPA_OPT_OUT_OPTION_MODE = "MspaOptOutOptionMode",
  MSPA_SERVICE_PROVIDER_MODE = "MspaServiceProviderMode",
}

export const USVAV1_CORE_SEGMENT_FIELD_NAMES = [
  UsVaV1Field.VERSION,
  UsVaV1Field.SHARING_NOTICE,
  UsVaV1Field.SALE_OPT_OUT_NOTICE,
  UsVaV1Field.TARGETED_ADVERTISING_OPT_OUT_NOTICE,
  UsVaV1Field.SALE_OPT_OUT,
  UsVaV1Field.TARGETED_ADVERTISING_OPT_OUT,
  UsVaV1Field.SENSITIVE_DATA_PROCESSING,
  UsVaV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS,
  UsVaV1Field.MSPA_COVERED_TRANSACTION,
  UsVaV1Field.MSPA_OPT_OUT_OPTION_MODE,
  UsVaV1Field.MSPA_SERVICE_PROVIDER_MODE,
];
